USE BurritoKingDB;
-- CREATE TABLE users (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     username VARCHAR(50) NOT NULL UNIQUE,
--     password VARCHAR(255) NOT NULL,
--     firstname VARCHAR(50),
--     lastname VARCHAR(50),
--     email VARCHAR(100) UNIQUE,
--     isVip BOOLEAN DEFAULT FALSE,
--     points INT DEFAULT 0
-- );
-- CREATE TABLE orders (
--     orderId INT AUTO_INCREMENT Primary key,
--     orderDetails VARCHAR(50),
--     status VARCHAR(50),
--     user VARCHAR(50),
--     total int,
--     dates datetime,
--     waitTime int
-- );